routes/web.php
    Route::resource('foreign-payment', 'ForeignPaymentController');
    //Local
    Route::resource('local-requisition', 'LocalRequisitionController');
    Route::resource('local-purchase-order', 'LocalPurchaseOrderController');
    Route::resource('quotation', 'QuotationController');
    Route::resource('quotation-compare', 'QuotationCompareController');
    //Procurement Setting
    Route::resource('vendor', 'VendorController');
    Route::resource('vendor-category', 'VendorCategoryController');
    Route::resource('business-nature', 'BusinessNatureController');
    Route::resource('business-type', 'BusinessTypeController');
    Route::resource('requisition-purpose', 'RequisitionPurposeController');
    Route::resource('cost-particular', 'CostParticularController');
    Route::resource('consignment-particular', 'ConsignmentParticularController');
    Route::resource('move-type', 'MoveTypeController');
    Route::resource('modes-of-transport', 'ModesOfTransportController');

    //CI Tracking
    Route::get('/commercial-invoice-tracking', ['as' => 'commercial-invoice-tracking.index', 'uses' => 'CommercialInvoiceTrackingController@index']);
    Route::get('/commercial-invoice-tracking/create', ['as' => 'get-ci-with-tracking', 'uses' => 'CommercialInvoiceTrackingController@getCIWithTracking']);
    Route::post('/commercial-invoice-tracking/save-tracking_date', ['as' => 'save-tracking-date', 'uses' => 'CommercialInvoiceTrackingController@saveDate']);

});

//Sales
Route::middleware('auth')->namespace('Sales')->prefix('sales')->group(function(){
    Route::resource('sales-order', 'SalesOrderController');
    Route::resource('sales-order-cancel', 'SalesOrderCancelController');
    Route::resource('sales-challan', 'SalesChallanController');
    Route::resource('sales-invoice', 'SalesInvoiceController');
    Route::resource('sales-invoice-cancel', 'SalesInvoiceCancelController');
    Route::resource('sales-invoice-received', 'SalesInvoiceReceivedController');
    Route::resource('collection-schedule', 'CollectionScheduleController');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('delivery-schedule', 'DeliveryScheduleController');
    Route::resource('invoice-schedule', 'InvoiceScheduleController');
    Route::resource('sales-order-return', 'SalesOrderReturnController');
    // Setting
    Route::resource('customer', 'CustomerController');
    Route::resource('customer-zone', 'CustomerZoneController');
    Route::resource('sales-return-reason', 'SalesReturnReasonController');
    Route::prefix('rule-setup')->group(function(){
        Route::get('/', 'RuleSetupController@index')->name('rule-setup');
        Route::resource('credit-rule', 'CreditRuleController');
        Route::resource('discount-customer-wise', 'DiscountCustomerWiseController');
        Route::resource('discount-generic', 'DiscountGenericController');
        Route::resource('free-bonus-customer-wise', 'FreeBonusCustomerWiseController');
        Route::resource('free-bonus-generic', 'FreeBonusGenericController');
        Route::resource('sales-order-cancel-reason', 'SalesOrderCancelReasonController');   
    });

});

//Accounts
Route::middleware('auth')->namespace('Accounts')->prefix('accounts')->group(function(){
    Route::resource('product-costing', 'ProductCostingController');
});

//Company
Route::middleware('auth')->namespace('Company')->prefix('company')->group(function(){
    Route::resource('company-profile', 'CompanyProfileController');
    Route::resource('company-bank', 'CompanyBankController');
    Route::resource('company-license', 'CompanyLicenseController');
    Route::resource('notification', 'NotificationController');
    Route::resource('department', 'DepartmentController');
    Route::resource('own-vehicle', 'OwnVehicleController');
});

//Inventory
Route::middleware(['auth', 'hasPermission:access_to_inventory', 'hasWorkingUnit'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('requisition', 'RequisitionController');
    Route::get('incoming/requisition', 'RequisitionController@incoming')->name('requisition.incoming');
    Route::get('incoming/requisition/{inventory_issue_request}', 'RequisitionController@show_incoming')->name('requisition.show_incoming');
    Route::resource('issue', 'IssueController');

    Route::resource('receive', 'ReceiveController');
    Route::resource('receive-internal', 'ReceiveInternalController');
    Route::resource('receive-foreign-purchase', 'ReceiveForeignPurchaseController');
    Route::resource('receive-local-purchase', 'ReceiveLocalPurchaseController');
    Route::resource('receive-return', 'ReceiveReturnController');

    Route::resource('status-adjustment', 'StatusAdjustmentController');
    Route::resource('stock-adjustment', 'StockAdjustmentController');
    //Route::resource('item-status', 'ItemStatusController');
    Route::resource('adjustment-purpose', 'AdjustmentPurposeController');
    Route::resource('return-reason', 'ReturnReasonController');
    Route::resource('requisition-type', 'RequisitionTypeController');
    Route::resource('record-type', 'RecordTypeController');
    Route::resource('stock-report', 'StockReportController');
    Route::resource('safety-stock', 'SafetyStockController');

});

Route::middleware(['auth'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('stock-report', 'StockReportController');

});

//Inventory Related API without auth middleware
Route::namespace('Inventory')->prefix('inventory')->group(function(){

    Route::get('get-product-info/{working_unit}/{product_status}/{product_type}/{slug}', 'RequisitionController@get_product_info');
    Route::get('get-product-info-for-adjustment/{working_unit}/{slug}', 'RequisitionController@get_product_info_for_adjustment');
    Route::get('vue-old-products/{working_unit}/{product_status}/{product_type}', 'RequisitionController@vue_old_products');
    Route::get('get-batch-stock/{working_unit}/{product_status}/{product_type}/{product}/{slug}', 'RequisitionController@get_batch_stock');

    //routes for receive product info
    Route::prefix('api')->group(function(){

        Route::get('vue-old-products', 'ReceiveController@vue_old_products');
        Route::get('vue-old-inputs', 'ReceiveController@vue_old_inputs');
        Route::get('get-product-info/{slug}', 'ReceiveController@get_product_info');
        Route::get('get-commercial-invoice/{slug}', 'ReceiveController@get_commercial_invoice');
        Route::get('get-purchase-order/{slug}', 'ReceiveController@get_purchase_order');
        Route::get('get-inventory-requisition/{working_unit}/{slug}', 'ReceiveController@get_inventory_requisition');
        Route::get('get-product-statuses', 'ReceiveController@product_statuses');
        Route::get('get-issue-return/{working_unit}/{slug}', 'ReceiveController@get_issue_return');

        //route for status adjustment
        Route::get('product-info-for-adjusment/{working_unit}/{selected_type}/{selected_status}/{slug}', 'StatusAdjustmentController@product_info_for_adjusment');
        Route::get('fetch-requisition/{requested_working_unit}/{slug}', 'IssueController@fetch_requisition');
        Route::get('get-batch-stock/{working_unit}/{product}/{inventory_requisition_no}/{slug}', 'IssueController@get_batch_stock');

        //route to fetch safety stock
        Route::get('fetch-safety-stock/{working_unit}/{product}', 'SafetyStockController@fetch_safety_stock');

    });

});

//Report
Route::middleware('auth')->namespace('Report')->prefix('report')->group(function(){
    Route::get('/foreign-purchase-order', ['as' => 'report-foreign-purchase-order', 'uses' => 'ProcurementReportController@foreign_purchase_order']);
    Route::get('/proforma-invoice', ['as' => 'report-proforma-invoice', 'uses' => 'ProcurementReportController@proforma_invoice']);
    Route::get('/commercial-invoice', ['as' => 'report-commercial-invoice', 'uses' => 'ProcurementReportController@commercial_invoice']);
});

//API

Route::get('/search-product', ['as' => 'search-product', 'uses' => 'ApiController@searchProduct']);
Route::get('/get-product/{id}', ['as' => 'get-product', 'uses' => 'ApiController@getProductByProductId']);
Route::get('/get-foreign-requisition/{ids}', ['as' => 'get-foreign-requisition', 'uses' => 'ApiController@getForeignRequisitionByRequisitionIds']);
Route::get('/get-local-requisition/{ids}', ['as' => 'get-local-requisition', 'uses' => 'ApiController@getLocalRequisitionByRequisitionIds']);
Route::get('/get-po/{ids}', ['as' => 'get-po', 'uses' => 'ApiController@getPOByPOIds']);
Route::get('/get-pi/{id}', ['as' => 'get-pi', 'uses' => 'ApiController@getPiByPiItem']);
Route::get('/get-lc/{id}', ['as' => 'get-lc', 'uses' => 'ApiController@getLcByLcId']);
Route::get('/get-all-product/{product_group_id}', ['as' => 'get-all-product', 'uses' => 'ApiController@getAllProduct']);
Route::get('/get-ci/{id}', ['as' => 'get-ci', 'uses' => 'ApiController@getCiByCiId']);
Route::get('/get-all-by-bl-no/{bl_no}', ['as' => 'get-all-by-bl-no', 'uses' => 'ApiController@getAllByBlNo']);
Route::get('/get-bl-by-bl-id/{id}', ['as' => 'get-bl-by-bl-id', 'uses' => 'ApiController@getBlByBlId']);
Route::get('/get-bank-info/{id}', ['as' => 'get-bank-info', 'uses' => 'ApiController@getBankInfoById']);
Route::get('/get-vendor-bank-info/{id}', ['as' => 'get-vendor-bank-info', 'uses' => 'ApiController@getVendorBankInfoById']);
Route::get('/get-due-amount/{id}/{no}', ['as' => 'et-due-amount', 'uses' => 'ApiController@getDueAmount']);
Route::get('/get-lc-to-ci-list/{id}', ['as' => 'get-lc-to-ci-list', 'uses' => 'ApiController@getLcToCiList']);
Route::get('/get-ci-by-ci-ids/{ids}', ['as' => 'get-ci-by-ci-ids', 'uses' => 'ApiController@getCIByCIIds']);
Route::get('/get-requisition-items-by-requisition-id/{id}', ['as' => 'get-requisition-items-by-requisition-id', 'uses' => 'ApiController@getRequisitionItemsForQuotationByLocalRequisitionId']);

app/Http/Controllers/Company/CompanyBankController.php
<?php

namespace App\Http\Controllers\Company;

use App\CompanyBank;
use App\CompanyProfile;
use App\Bank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Session;

class CompanyBankController extends Controller
{
    private $view_root = 'modules/company/company_bank/';

    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('bank_list', CompanyBank::all());
        return $view;
    }

    public function create()
    {
        $view = view($this->view_root . 'create');
        $view->with('company_list', CompanyProfile::pluck('name', 'id')->prepend('--select company--', ''));
        $view->with('bank_list', Bank::pluck('name', 'id')->prepend('--select bank--', ''));
        return $view;
    }

    public function store(Request $request)
    {
        $request->validate([
            'account_no' => 'required|unique:company_banks',
            'account_name' => 'required',
            'bank_id' => 'required',
            'company_id' => 'required',
            'branch_name' => 'required',
            'swift_code' => 'required',
        ]);
        $bank = new CompanyBank;
        $bank->fill($request->input());
        $bank->creator_user_id = Auth::id();
        $bank->save();
        Session::put('alert-success', 'New bank information added successfully');
        return redirect()->route('company-bank.index');
    }

    public function show(CompanyBank $companyBank)
    {
        $view = view($this->view_root . 'show');
        $view->with('companyBank', $companyBank);
        return $view;
    }

    public function edit(CompanyBank $companyBank)
    {
        $view = view($this->view_root . 'edit');
        $view->with('company_list', CompanyProfile::pluck('name', 'id')->prepend('--select company--', ''));
        $view->with('bank_list', Bank::pluck('name', 'id')->prepend('--select bank--', ''));
        $view->with('companyBank', $companyBank);
        return $view;
    }

    public function update(Request $request, CompanyBank $companyBank)
    {

        $request->validate([
            'account_no' => 'required|unique:company_banks,account_no,'.$companyBank->id,
            'account_name' => 'required',
            'bank_id' => 'required',
            'company_id' => 'required',
            'branch_name' => 'required',
            'swift_code' => 'required',
        ]);
      
        $companyBank->fill($request->all());
        $companyBank->update();
        Session::put('alert-success',$companyBank->name . ' updated successfully!');
        return redirect()->route('company-bank.index');
    }

    public function destroy(CompanyBank $companyBank)
    {
        //
    }
}

app/Http/Controllers/Company/CompanyLicenseController.php
<?php

namespace App\Http\Controllers\Company;
use App\Http\Controllers\Controller;
use App\CompanyLicense;
use App\CompanyProfile;
use Illuminate\Http\Request;
use Session;
use Auth;


class CompanyLicenseController extends Controller
{
    private $view_root = 'modules/company/company_license/';

    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('company_license_list', CompanyLicense::all());
        return $view;
    }

    
    public function create()
    {
        $view = view($this->view_root . 'create');
        $view->with('company_profile_list', CompanyProfile::pluck('name', 'id')->prepend('-- Select Company --', ''));
        return $view;
    }

    public function store(Request $request)
    {
        $request->validate([
            'company_profile_id'=> 'required',
            'license_name'=> 'required',
            'license_no'=> 'required',
            'renewed_date'=> 'required',
            'expire_date'=> 'required'
        ]);
        $companyLicense = new CompanyLicense;
        $companyLicense->fill($request->input());
        $companyLicense->creator_user_id = Auth::id();
        $companyLicense->save();
        Session::put('alert-success', $companyLicense->name .' created successfully.');
        return redirect()->route('company-license.index');
    }

    public function show(CompanyLicense $companyLicense)
    {
        $view = view($this->view_root . 'show');
        $view->with('companyLicense', $companyLicense);
        return $view;
    }

    public function edit(CompanyLicense $companyLicense)
    {
        $view = view($this->view_root . 'edit');
        $view->with('company_profile_list', CompanyProfile::pluck('name', 'id')->prepend('-- Select Company --', ''));
        $view->with('companyLicense',$companyLicense);
        return $view;
    }

    public function update(Request $request, CompanyLicense $companyLicense)
    {
        $request->validate([
            'company_profile_id'=> 'required',
            'license_name'=> 'required',
            'license_no'=> 'required',
            'renewed_date'=> 'required',
            'expire_date'=> 'required'
        ]);
        $companyLicense->fill($request->all());
        $companyLicense->update();
        Session::put('alert-success', $companyLicense->license_name .' updated successfully!');
        return redirect()->route('company-license.index');
    }

    public function destroy(CompanyLicense $companyLicense)
    {
        //
    }
}

app/Http/Controllers/Company/CompanyProfileController.php
<?php

namespace App\Http\Controllers\Company;

use App\CompanyProfile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Country;
use Auth;
use Session;

class CompanyProfileController extends Controller
{
    private $view_root = 'modules/company/general_information/';

    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('company_list', CompanyProfile::all());
        return $view;
    }

    public function create()
    {
        $view = view($this->view_root . 'create');
        $view->with('country_list', Country::pluck('name', 'id')->prepend('select country', ''));
        return $view;
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:company_profiles',
            'email' => 'required',
            'phone' => 'required',
        ]);

        $company_profile = new CompanyProfile;
        $company_profile->fill($request->input());
        $company_profile->creator_user_id = Auth::id();
        $company_profile->save();
        Session::put('alert-success', $company_profile->name . ' created successfully');
        return redirect()->route('company-profile.index');
    }

    public function show(CompanyProfile $companyProfile)
    {
        $view = view($this->view_root . 'show');
        $view->with('companyProfile', $companyProfile);
        return $view;
    }

    public function edit(CompanyProfile $companyProfile)
    {
        $view = view($this->view_root . 'edit');
        $view->with('country_list', Country::pluck('name', 'id')->prepend('select country', ''));
        $view->with('companyProfile',$companyProfile );
        return $view;
    }

    public function update(Request $request, CompanyProfile $companyProfile)
    {
        {
            $request->validate([
                'name' => 'required|unique:company_profiles,name,'.$companyProfile->id,
                'email' => 'required|unique:company_profiles,email,'.$companyProfile->id,
            ]);

            $companyProfile->fill($request->all());
            $companyProfile->update();
            Session::put('alert-success',$companyProfile->name . ' updated successfully!');
            return redirect()->route('company-profile.index');
        }
    }

    public function destroy(CompanyProfile $companyProfile)
    {
        //
    }
}

resources/views/modules/company/general_information/create.blade.php
@extends('layout')
@section('title', 'Company General Information')
@section('content')
<div class="right_col" role="main">
        <div class="page-title">
            <div class="title_left">
                <h3>Company Setting</h3>
            </div>
        </div>
        <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>General Information</h2>
                    <a class="btn btn-primary btn-sm pull-right" href="{{route('company-profile.index')}}"><i class="fa fa-list"></i> General Information List</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    @include('partials.flash_msg')
                    <form class="form-horizontal form-label-left" action="{{ route('company-profile.store') }}" method="POST" autocomplete="off">
                        @csrf
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::text('name','Company Name', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::email('email','Email', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::tel('phone','Phone Number', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::tel('telephone','Telephone Number', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::text('fax','Fax', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::text('website','Website', null, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::select('country_id', 'Country', $country_list, null, ['class'=>'form-control input-sm select2', 'data-popup'=>route('country.index')]) }}
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            {{ BootForm::textarea('address','Address', null, ['class'=>'form-control input-sm', 'rows' => '3']) }}
                        </div>
                        <br>
                        <hr>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <br />
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Save</button>
                                <a class="btn btn-default" href="{{route('company-profile.index')}}">Cancel</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

  </div>
@endsection

resources/views/modules/company/general_information/edit.blade.php
@extends('layout')
@section('title', 'Company General Information')
@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Company Setting</h3>
            </div>
        </div>
        <div class="clearfix"></div>
      <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                  <div class="x_title">
                      <h2>General Information</h2>
                      <a class="btn btn-primary btn-sm pull-right" href="{{route('company-profile.index')}}"><i class="fa fa-list"></i> Company General Information List</a>
                      <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                    @include('partials.flash_msg')
                    <form class="form-horizontal form-label-left" action="{{ route('company-profile.update',$companyProfile) }}" method="POST" autocomplete="off">
                    <input name="_method" type="hidden" value="PUT"> 
                        @csrf
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::text('name','Company Name', $companyProfile->name, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::email('email','Email', $companyProfile->email, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::tel('phone','Phone Number', $companyProfile->phone, ['class'=>'form-control input-sm']) }}
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ BootForm::select('country_id', 'Country', $country_list, $companyProfile->country_id, ['class'=>'form-control input-sm select2']) }}
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            {{ BootForm::textarea('address','Address', $companyProfile->address, ['class'=>'form-control input-sm', 'rows' => '3']) }}
                        </div>
                        <br>
                        <hr>
                      <div class="col-md-12 col-sm-12 col-xs-12">
                          <br />
                          <div class="ln_solid"></div>
                          <div class="form-group">
                              <button type="submit" class="btn btn-success">Update</button>
                              <a class="btn btn-default" href="{{route('company-profile.index')}}">Cancel</a>
                          </div>
                      </div>
                    </form>

                  </div>
              </div>
          </div>
          </div>
      <div class="clearfix"></div>
    </div>
  </div>
@endsection

resources/views/modules/company/general_information/index.blade.php
@extends('layout')
@section('title', 'Company General Information')
@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Company Setting</h3>
            </div>
        </div>
        <div class="clearfix"></div>
      <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
                    <div class="x_title">
                        <h2>General Information</h2>
                        <a href="{{ route('company-profile.create') }}" class="btn btn-sm btn-primary btn-addon pull-right"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" id="popup_area">
                        <br />
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover datatable-buttons">
                                <thead class="bg-primary">
                                    <tr>
                                        <th width="25">#</th>
                                        <th>Company Name</th>
                                        <th>Phone Number</th>
                                        <th>Country</th>
                                        <th class="text-center" width="75px">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($company_list as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->phone }}</td>
                                        <td>{{ $item->country->name }}</td>
                                        
                                        <td class="text-center">
                                            <div class="btn-group" role="group" aria-label="...">
                                                <div class="btn-group" role="group">
                                                <a href="{{ route('company-profile.edit',$item) }}" type="button" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i>Edit</a>
                                                </div>
                                                <div class="btn-group" role="group">
                                                <a href="{{ route('company-profile.show',$item) }}" type="button" class="btn btn-default btn-xs"><i class="fa fa-eye"></i>View</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!--end table-->
                    </div>
                </div>
          </div>
          </div>
      <div class="clearfix"></div>
    </div>
  </div>
@endsection

resources/views/modules/company/general_information/show.blade.php
@extends('layout')
@section('title', 'Company General Information')
@section('content')
<!-- page content -->
        <div class="right_col" role="main">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Company General Information</h2>
                        <a href="{{route('company-profile.index')}}" class="btn btn-sm btn-primary btn-addon pull-right"><i class="fa fa-list-ul" aria-hidden="true"></i>  Company General Information List</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <th width="300">Company Name:</th>
                                            <td>{{$companyProfile->name}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Email:</th>
                                            <td>{{$companyProfile->email}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Phone Number:</th>
                                            <td>{{$companyProfile->phone}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Telephone Number:</th>
                                            <td>{{$companyProfile->telephone}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Fax:</th>
                                            <td>{{$companyProfile->fax}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Website:</th>
                                            <td>{{$companyProfile->website}}</td>       
                                        </tr>
                                        <tr>
                                            <th>Address:</th>
                                            <td>{{$companyProfile->address}}</td>       
                                        </tr>
                                   
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
@endsection