routes/web.php
<?php

Route::get('/test', 'TestController@index');
Route::get('/design', 'TestController@design');

Route::namespace('Dev')->prefix('dev')->group(function(){

});

//Common
Auth::routes();
Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index'])->middleware('auth');
Route::get('/get_toaster_notification', ['as' => 'get_toaster_notification', 'uses' => 'HomeController@get_toaster_notification']);

//Core
Route::middleware('auth')->namespace('Core')->prefix('core')->group(function(){
    Route::resource('working-unit', 'WorkingUnitController');
    Route::resource('country', 'CountryController');
    Route::resource('division', 'DivisionController');
    Route::resource('district', 'DistrictController');
    Route::resource('city', 'CityController');
    Route::resource('port', 'PortController');
    Route::resource('product-brand', 'ProductBrandController');
    Route::resource('product-category', 'ProductCategoryController');
    Route::resource('unit-of-measurement', 'UnitOfMeasurementController');
    Route::resource('product-model', 'ProductModelController');
    Route::resource('product-size', 'ProductSizeController');
    Route::resource('product', 'ProductController');
    Route::resource('bank', 'BankController');
    Route::resource('enclosure', 'EnclosureController');
    Route::resource('employee-profile', 'EmployeeProfileController');
    Route::resource('payment-type', 'PaymentTypeController');
    Route::resource('terms-and-condition-type', 'TermsAndConditionTypeController');

    Route::get(
        'employee-organizational-info/{organizational_info}', 'EmployeeProfileController@organizational_info_form'
    )->name('employee-profile.organizational-info');

    Route::put(
        'employee-organizational-info/{organizational_info}', 'EmployeeProfileController@update_organizational_info'
    )->name('employee-profile.update-organizational-info');

    Route::resource('employee-user', 'EmployeeUserController');
    Route::get('country-detail', 'CountryController@country_detail');
    Route::resource('designation', 'DesignationController');

});

//Core related API without auth middleware
Route::namespace('Core')->prefix('core')->group(function(){

    Route::get('country-detail', 'CountryController@country_detail');

});


//Procurement
Route::middleware('auth')->namespace('Procurement')->prefix('procurement')->group(function(){
    // Foreign
    Route::resource('foreign-requisition', 'ForeignRequisitionController');
    Route::resource('purchase-order', 'PurchaseOrderController');
    Route::resource('proforma-invoice', 'ProformaInvoiceController');
    Route::resource('letter-of-credit', 'LetterOfCreditController');
    Route::resource('cost-sheet', 'CostSheetController');
    Route::resource('insurance-cover-note', 'InsuranceCoverNoteController');
    Route::resource('commercial-invoice', 'CommercialInvoiceController');
    Route::resource('packing-list', 'PackingListController');
    Route::resource('bill-of-lading', 'BillOfLadingController');
    Route::resource('cnf', 'CnfController');
    Route::resource('foreign-payment', 'ForeignPaymentController');
    //Local
    Route::resource('local-requisition', 'LocalRequisitionController');
    Route::resource('local-purchase-order', 'LocalPurchaseOrderController');
    Route::resource('quotation', 'QuotationController');
    Route::resource('quotation-compare', 'QuotationCompareController');
    //Procurement Setting
    Route::resource('vendor', 'VendorController');
    Route::resource('vendor-category', 'VendorCategoryController');
    Route::resource('business-nature', 'BusinessNatureController');
    Route::resource('business-type', 'BusinessTypeController');
    Route::resource('requisition-purpose', 'RequisitionPurposeController');
    Route::resource('cost-particular', 'CostParticularController');
    Route::resource('consignment-particular', 'ConsignmentParticularController');
    Route::resource('move-type', 'MoveTypeController');
    Route::resource('modes-of-transport', 'ModesOfTransportController');

    //CI Tracking
    Route::get('/commercial-invoice-tracking', ['as' => 'commercial-invoice-tracking.index', 'uses' => 'CommercialInvoiceTrackingController@index']);
    Route::get('/commercial-invoice-tracking/create', ['as' => 'get-ci-with-tracking', 'uses' => 'CommercialInvoiceTrackingController@getCIWithTracking']);
    Route::post('/commercial-invoice-tracking/save-tracking_date', ['as' => 'save-tracking-date', 'uses' => 'CommercialInvoiceTrackingController@saveDate']);

});

//Sales
Route::middleware('auth')->namespace('Sales')->prefix('sales')->group(function(){
    Route::resource('sales-order', 'SalesOrderController');
    Route::resource('sales-order-cancel', 'SalesOrderCancelController');
    Route::resource('sales-challan', 'SalesChallanController');
    Route::resource('sales-invoice', 'SalesInvoiceController');
    Route::resource('sales-invoice-cancel', 'SalesInvoiceCancelController');
    Route::resource('sales-invoice-received', 'SalesInvoiceReceivedController');
    Route::resource('collection-schedule', 'CollectionScheduleController');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('delivery-schedule', 'DeliveryScheduleController');
    Route::resource('invoice-schedule', 'InvoiceScheduleController');
    Route::resource('sales-order-return', 'SalesOrderReturnController');
    // Setting
    Route::resource('customer', 'CustomerController');
    Route::resource('customer-zone', 'CustomerZoneController');
    Route::resource('sales-return-reason', 'SalesReturnReasonController');
    Route::prefix('rule-setup')->group(function(){
        Route::get('/', 'RuleSetupController@index')->name('rule-setup');
        Route::resource('credit-rule', 'CreditRuleController');
        Route::resource('discount-customer-wise', 'DiscountCustomerWiseController');
        Route::resource('discount-generic', 'DiscountGenericController');
        Route::resource('free-bonus-customer-wise', 'FreeBonusCustomerWiseController');
        Route::resource('free-bonus-generic', 'FreeBonusGenericController');
        Route::resource('sales-order-cancel-reason', 'SalesOrderCancelReasonController');   
    });

});

//Accounts
Route::middleware('auth')->namespace('Accounts')->prefix('accounts')->group(function(){
    Route::resource('product-costing', 'ProductCostingController');
});

//Company
Route::middleware('auth')->namespace('Company')->prefix('company')->group(function(){
    Route::resource('company-profile', 'CompanyProfileController');
    Route::resource('company-bank', 'CompanyBankController');
    Route::resource('company-license', 'CompanyLicenseController');
    Route::resource('notification', 'NotificationController');
    Route::resource('department', 'DepartmentController');
    Route::resource('own-vehicle', 'OwnVehicleController');
});

//Inventory
Route::middleware(['auth', 'hasPermission:access_to_inventory', 'hasWorkingUnit'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('requisition', 'RequisitionController');
    Route::get('incoming/requisition', 'RequisitionController@incoming')->name('requisition.incoming');
    Route::get('incoming/requisition/{inventory_issue_request}', 'RequisitionController@show_incoming')->name('requisition.show_incoming');
    Route::resource('issue', 'IssueController');

    Route::resource('receive', 'ReceiveController');
    Route::resource('receive-internal', 'ReceiveInternalController');
    Route::resource('receive-foreign-purchase', 'ReceiveForeignPurchaseController');
    Route::resource('receive-local-purchase', 'ReceiveLocalPurchaseController');
    Route::resource('receive-return', 'ReceiveReturnController');

    Route::resource('status-adjustment', 'StatusAdjustmentController');
    Route::resource('stock-adjustment', 'StockAdjustmentController');
    //Route::resource('item-status', 'ItemStatusController');
    Route::resource('adjustment-purpose', 'AdjustmentPurposeController');
    Route::resource('return-reason', 'ReturnReasonController');
    Route::resource('requisition-type', 'RequisitionTypeController');
    Route::resource('record-type', 'RecordTypeController');
    Route::resource('stock-report', 'StockReportController');
    Route::resource('safety-stock', 'SafetyStockController');

});

Route::middleware(['auth'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('stock-report', 'StockReportController');

});

//Inventory Related API without auth middleware
Route::namespace('Inventory')->prefix('inventory')->group(function(){

    Route::get('get-product-info/{working_unit}/{product_status}/{product_type}/{slug}', 'RequisitionController@get_product_info');
    Route::get('get-product-info-for-adjustment/{working_unit}/{slug}', 'RequisitionController@get_product_info_for_adjustment');
    Route::get('vue-old-products/{working_unit}/{product_status}/{product_type}', 'RequisitionController@vue_old_products');
    Route::get('get-batch-stock/{working_unit}/{product_status}/{product_type}/{product}/{slug}', 'RequisitionController@get_batch_stock');

    //routes for receive product info
    Route::prefix('api')->group(function(){

        Route::get('vue-old-products', 'ReceiveController@vue_old_products');
        Route::get('vue-old-inputs', 'ReceiveController@vue_old_inputs');
        Route::get('get-product-info/{slug}', 'ReceiveController@get_product_info');
        Route::get('get-commercial-invoice/{slug}', 'ReceiveController@get_commercial_invoice');
        Route::get('get-purchase-order/{slug}', 'ReceiveController@get_purchase_order');
        Route::get('get-inventory-requisition/{working_unit}/{slug}', 'ReceiveController@get_inventory_requisition');
        Route::get('get-product-statuses', 'ReceiveController@product_statuses');

app/Http/Controllers/Core/BankAccountController.php
<?php

namespace App\Http\Controllers\Core;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BankAccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Core/BankController.php
<?php

namespace App\Http\Controllers\Core;

use App\Bank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Country;
use Auth;
use Session;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $view_root = 'modules/core/bank/';

    public function index()
    {
        // $data = [
        //     'countries' => \App\Country::pluck( 'name', 'id')
        // ];

        $view = view($this->view_root . 'index');
        $view->with('bank_list', Bank::all());
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));

        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view($this->view_root.'create');
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:banks',
            'country_id' => 'required',
            'short_name' => 'required|unique:banks',
            'description' => 'required'
        ]);

        $bank = new Bank;
        $bank->fill($request->input());
        $bank->creator_user_id = Auth::id();
        $bank->save();
        Session::put('alert-success', $bank->name . " successfully created");
        return redirect()->route('bank.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        dd('fff');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {
        $view = view($this->view_root . 'edit');
        $view->with('bank', $bank);
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));

        return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        $request->validate([
            'name' => 'required|unique:product_models,name,'.$bank->id,
            'short_name' => 'required|unique:product_models,short_name,'.$bank->id,
            'country_id' => 'required',
            'description' => 'required'
        ]);
        $bank->fill($request->all());
        $bank->update();
        Session::put('alert-success',$bank->name . ' updated successfully!');
        return redirect()->route('bank.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        //
    }
}

app/Http/Controllers/Core/CityController.php
<?php

namespace App\Http\Controllers\Core;

use App\City;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Country;
use Auth;
use Session;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $view_root = 'modules/core/city/';

    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('city_list', City::all());
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view($this->view_root.'create');
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:cities',
            'country_id' => 'required'
        ]);

        $city = new City;
        $city->fill($request->input());
        $city->creator_user_id = Auth::id();
        $city->save();
        Session::put('alert-success', $city->name . " successfully created");
        return redirect()->route('city.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        $view = view($this->view_root . 'edit');
        $view->with('city_info',$city);
        $view->with('country_list', Country::pluck('name', 'id')->prepend('--select country--', ''));
        return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
      
      $request->validate([
        'name' => 'required|unique:cities,name,'.$city->id,
        'country_id' => 'required'
    ]);

    $city->fill($request->all());
    if($city->save()) return back()->with('success', 'Form edited successfully');
    return back()->with('danger', 'Form Submission failed!.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        //
    }
}

resources/views/modules/core/terms_and_condition_type/create.blade.php
@extends('layout')
@section('title', 'Terms And Condition Type')
@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Master Data</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Terms And Condition Type</h2>
                        <a class="btn btn-primary btn-sm pull-right" href="{{route('terms-and-condition-type.index')}}"><i class="fa fa-list"></i> Payment Type List</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        {{-- @include('partials.flash_msg') --}}
                        <form class="form-horizontal form-label-left" action="{{route('terms-and-condition-type.store')}}" method="POST" autocomplete="off">
                            {{csrf_field()}}
                            <div class="col-md-6 offset-md-3 col-sm-6 col-xs-12">
                                {{ BootForm::text('name', 'Name', null, ['class'=>'form-control input-sm','required'=>'required']) }}
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ BootForm::text('short_name', 'Short Name', null, ['class'=>'form-control input-sm','required'=>'required']) }}
                            </div>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <br />
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <a class="btn btn-default" href="{{route('terms-and-condition-type.index')}}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
@endsection

resources/views/modules/core/terms_and_condition_type/edit.blade.php
@extends('layout')
@section('title', 'Terms And Condition Type')
@section('content')
<div class="right_col" role="main">
    <div class="">
@php
//dd($terms_and_condition_type_list);
@endphp
        <div class="page-title">
            <div class="title_left">
                <h3>Master Data</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Terms And Condition Type</h2>
                        <a class="btn btn-primary btn-sm pull-right" href="{{route('terms-and-condition-type.index')}}"><i class="fa fa-list"></i> Payment Type List</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        {{-- @include('partials.flash_msg') --}}
                        <form class="form-horizontal form-label-left" action="{{route('terms-and-condition-type.update',$termsAndConditionType)}}" method="POST" autocomplete="off">
                        <input name="_method" type="hidden" value="PUT"> 
                         {{csrf_field()}}
                            <div class="col-md-6 offset-md-3 col-sm-6 col-xs-12">
                                {{ BootForm::text('name', 'Name', $termsAndConditionType->name, ['class'=>'form-control input-sm','required'=>'required']) }}
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                {{ BootForm::text('short_name', 'Short Name',$termsAndConditionType->short_name, ['class'=>'form-control input-sm','required'=>'required']) }}
                            </div>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <br />
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-sm">Update</button>
                                    <a class="btn btn-default btn-sm" href="{{route('terms-and-condition-type.index')}}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
@endsection

resources/views/modules/core/terms_and_condition_type/index.blade.php
@extends('layout')
@section('title', 'Terms And Condition Type')
@section('content')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Master Data</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Terms Condition Type</h2>
                        <a href="{{ route('terms-and-condition-type.create') }}" class="btn btn-sm btn-primary btn-addon pull-right"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" id="popup_area">
                        <br />
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover datatable-buttons">
                                <thead class="bg-primary">
                                    <tr>
                                        <th width="25">#</th>
                                        <th>Name</th>
                                        <th>Short Name</th>
                                        <th  class="text-center" width="40">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($terms_and_condition_type_list as $key => $item)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->short_name }}</td>
                                        <td class="text-center"><a href="{{ route('terms-and-condition-type.edit',$item) }}" type="button" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i>Edit</a></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!--end table-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
@endsection