routes/web.php
    Route::resource('bank', 'BankController');
    Route::resource('enclosure', 'EnclosureController');
    Route::resource('employee-profile', 'EmployeeProfileController');
    Route::resource('payment-type', 'PaymentTypeController');
    Route::resource('terms-and-condition-type', 'TermsAndConditionTypeController');

    Route::get(
        'employee-organizational-info/{organizational_info}', 'EmployeeProfileController@organizational_info_form'
    )->name('employee-profile.organizational-info');

    Route::put(
        'employee-organizational-info/{organizational_info}', 'EmployeeProfileController@update_organizational_info'
    )->name('employee-profile.update-organizational-info');

    Route::resource('employee-user', 'EmployeeUserController');
    Route::get('country-detail', 'CountryController@country_detail');
    Route::resource('designation', 'DesignationController');

});

//Core related API without auth middleware
Route::namespace('Core')->prefix('core')->group(function(){

    Route::get('country-detail', 'CountryController@country_detail');

});


//Procurement
Route::middleware('auth')->namespace('Procurement')->prefix('procurement')->group(function(){
    // Foreign
    Route::resource('foreign-requisition', 'ForeignRequisitionController');
    Route::resource('purchase-order', 'PurchaseOrderController');
    Route::resource('proforma-invoice', 'ProformaInvoiceController');
    Route::resource('letter-of-credit', 'LetterOfCreditController');
    Route::resource('cost-sheet', 'CostSheetController');
    Route::resource('insurance-cover-note', 'InsuranceCoverNoteController');
    Route::resource('commercial-invoice', 'CommercialInvoiceController');
    Route::resource('packing-list', 'PackingListController');
    Route::resource('bill-of-lading', 'BillOfLadingController');
    Route::resource('cnf', 'CnfController');
    Route::resource('foreign-payment', 'ForeignPaymentController');
    //Local
    Route::resource('local-requisition', 'LocalRequisitionController');
    Route::resource('local-purchase-order', 'LocalPurchaseOrderController');
    Route::resource('quotation', 'QuotationController');
    Route::resource('quotation-compare', 'QuotationCompareController');
    //Procurement Setting
    Route::resource('vendor', 'VendorController');
    Route::resource('vendor-category', 'VendorCategoryController');
    Route::resource('business-nature', 'BusinessNatureController');
    Route::resource('business-type', 'BusinessTypeController');
    Route::resource('requisition-purpose', 'RequisitionPurposeController');
    Route::resource('cost-particular', 'CostParticularController');
    Route::resource('consignment-particular', 'ConsignmentParticularController');
    Route::resource('move-type', 'MoveTypeController');
    Route::resource('modes-of-transport', 'ModesOfTransportController');

    //CI Tracking
    Route::get('/commercial-invoice-tracking', ['as' => 'commercial-invoice-tracking.index', 'uses' => 'CommercialInvoiceTrackingController@index']);
    Route::get('/commercial-invoice-tracking/create', ['as' => 'get-ci-with-tracking', 'uses' => 'CommercialInvoiceTrackingController@getCIWithTracking']);
    Route::post('/commercial-invoice-tracking/save-tracking_date', ['as' => 'save-tracking-date', 'uses' => 'CommercialInvoiceTrackingController@saveDate']);

});

//Sales
Route::middleware('auth')->namespace('Sales')->prefix('sales')->group(function(){
    Route::resource('sales-order', 'SalesOrderController');
    Route::resource('sales-order-cancel', 'SalesOrderCancelController');
    Route::resource('sales-challan', 'SalesChallanController');
    Route::resource('sales-invoice', 'SalesInvoiceController');
    Route::resource('sales-invoice-cancel', 'SalesInvoiceCancelController');
    Route::resource('sales-invoice-received', 'SalesInvoiceReceivedController');
    Route::resource('collection-schedule', 'CollectionScheduleController');
    Route::resource('payment-schedule', 'PaymentScheduleController');
    Route::resource('delivery-schedule', 'DeliveryScheduleController');
    Route::resource('invoice-schedule', 'InvoiceScheduleController');
    Route::resource('sales-order-return', 'SalesOrderReturnController');
    // Setting
    Route::resource('customer', 'CustomerController');
    Route::resource('customer-zone', 'CustomerZoneController');
    Route::resource('sales-return-reason', 'SalesReturnReasonController');
    Route::prefix('rule-setup')->group(function(){
        Route::get('/', 'RuleSetupController@index')->name('rule-setup');
        Route::resource('credit-rule', 'CreditRuleController');
        Route::resource('discount-customer-wise', 'DiscountCustomerWiseController');
        Route::resource('discount-generic', 'DiscountGenericController');
        Route::resource('free-bonus-customer-wise', 'FreeBonusCustomerWiseController');
        Route::resource('free-bonus-generic', 'FreeBonusGenericController');
        Route::resource('sales-order-cancel-reason', 'SalesOrderCancelReasonController');   
    });

});

//Accounts
Route::middleware('auth')->namespace('Accounts')->prefix('accounts')->group(function(){
    Route::resource('product-costing', 'ProductCostingController');
});

//Company
Route::middleware('auth')->namespace('Company')->prefix('company')->group(function(){
    Route::resource('company-profile', 'CompanyProfileController');
    Route::resource('company-bank', 'CompanyBankController');
    Route::resource('company-license', 'CompanyLicenseController');
    Route::resource('notification', 'NotificationController');
    Route::resource('department', 'DepartmentController');
    Route::resource('own-vehicle', 'OwnVehicleController');
});

//Inventory
Route::middleware(['auth', 'hasPermission:access_to_inventory', 'hasWorkingUnit'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('requisition', 'RequisitionController');
    Route::get('incoming/requisition', 'RequisitionController@incoming')->name('requisition.incoming');
    Route::get('incoming/requisition/{inventory_issue_request}', 'RequisitionController@show_incoming')->name('requisition.show_incoming');
    Route::resource('issue', 'IssueController');

    Route::resource('receive', 'ReceiveController');
    Route::resource('receive-internal', 'ReceiveInternalController');
    Route::resource('receive-foreign-purchase', 'ReceiveForeignPurchaseController');
    Route::resource('receive-local-purchase', 'ReceiveLocalPurchaseController');
    Route::resource('receive-return', 'ReceiveReturnController');

    Route::resource('status-adjustment', 'StatusAdjustmentController');
    Route::resource('stock-adjustment', 'StockAdjustmentController');
    //Route::resource('item-status', 'ItemStatusController');
    Route::resource('adjustment-purpose', 'AdjustmentPurposeController');
    Route::resource('return-reason', 'ReturnReasonController');
    Route::resource('requisition-type', 'RequisitionTypeController');
    Route::resource('record-type', 'RecordTypeController');
    Route::resource('stock-report', 'StockReportController');
    Route::resource('safety-stock', 'SafetyStockController');

});

Route::middleware(['auth'])->namespace('Inventory')->prefix('inventory')->group(function(){

    Route::resource('stock-report', 'StockReportController');

});

//Inventory Related API without auth middleware
Route::namespace('Inventory')->prefix('inventory')->group(function(){

    Route::get('get-product-info/{working_unit}/{product_status}/{product_type}/{slug}', 'RequisitionController@get_product_info');
    Route::get('get-product-info-for-adjustment/{working_unit}/{slug}', 'RequisitionController@get_product_info_for_adjustment');
    Route::get('vue-old-products/{working_unit}/{product_status}/{product_type}', 'RequisitionController@vue_old_products');
    Route::get('get-batch-stock/{working_unit}/{product_status}/{product_type}/{product}/{slug}', 'RequisitionController@get_batch_stock');

    //routes for receive product info
    Route::prefix('api')->group(function(){

        Route::get('vue-old-products', 'ReceiveController@vue_old_products');
        Route::get('vue-old-inputs', 'ReceiveController@vue_old_inputs');
        Route::get('get-product-info/{slug}', 'ReceiveController@get_product_info');
        Route::get('get-commercial-invoice/{slug}', 'ReceiveController@get_commercial_invoice');
        Route::get('get-purchase-order/{slug}', 'ReceiveController@get_purchase_order');
        Route::get('get-inventory-requisition/{working_unit}/{slug}', 'ReceiveController@get_inventory_requisition');
        Route::get('get-product-statuses', 'ReceiveController@product_statuses');
        Route::get('get-issue-return/{working_unit}/{slug}', 'ReceiveController@get_issue_return');

        //route for status adjustment
        Route::get('product-info-for-adjusment/{working_unit}/{selected_type}/{selected_status}/{slug}', 'StatusAdjustmentController@product_info_for_adjusment');
        Route::get('fetch-requisition/{requested_working_unit}/{slug}', 'IssueController@fetch_requisition');
        Route::get('get-batch-stock/{working_unit}/{product}/{inventory_requisition_no}/{slug}', 'IssueController@get_batch_stock');

        //route to fetch safety stock
        Route::get('fetch-safety-stock/{working_unit}/{product}', 'SafetyStockController@fetch_safety_stock');

    });

});

//Report
Route::middleware('auth')->namespace('Report')->prefix('report')->group(function(){
    Route::get('/foreign-purchase-order', ['as' => 'report-foreign-purchase-order', 'uses' => 'ProcurementReportController@foreign_purchase_order']);
    Route::get('/proforma-invoice', ['as' => 'report-proforma-invoice', 'uses' => 'ProcurementReportController@proforma_invoice']);
    Route::get('/commercial-invoice', ['as' => 'report-commercial-invoice', 'uses' => 'ProcurementReportController@commercial_invoice']);
});

//API

app/SalesOrderCancel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SalesOrderCancel extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'sales_order_id',
        'sales_order_cancel_reason_id',
        'remarks'
    ];

    public function sales_order(){
        return $this->belongsTo('App\SalesOrder');
    }

    public function sales_order_cancel_reason(){
        return $this->belongsTo('App\SalesOrderCancelReason');
    }

    public function generate_sales_order_cancel_number(){
        $serial = $this->count_last_serial() + 1;
        $this->sales_order_cancel_no =  'SO-Cancel-'.date('Y-m-').str_pad($serial, 4, '0', STR_PAD_LEFT);
    }

    private function count_last_serial(){
        return SalesOrderCancel::whereYear('created_at', date('Y'))
                            ->whereMonth('created_at', date('m'))
                            ->count();
    }
}

app/Http/Controllers/Sales/CollectionScheduleController.php
<?php

namespace App\Http\Controllers\Sales;

use App\CollectionSchedule;
use App\CollectionScheduleItem;
use App\SalesInvoice;
use App\Customer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Session;

class CollectionScheduleController extends Controller
{
    private $view_root = 'modules/sales/collection_schedule/';
    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('collection_schedule_list', CollectionSchedule::all());
        return $view;
    }

    public function create()
    {
        $view = view($this->view_root . 'create');
        $view->with('customer_list', Customer::pluck('name','id')->prepend('-- Select Customer --', ''));
        return $view;
    }

    public function store(Request $request)
    {
        //dd($request->input());
        $request->validate([  
            'customer_id' => 'required'
        ]);
        $collection_schedule = new CollectionSchedule;
        $collection_schedule->fill($request->input());
        $collection_schedule->creator_user_id = Auth::id();
       // $collection_schedule->collection_schedule_no = 'SC001';
       $collection_schedule->collection_schedule_no = uCode('collection_schedules.collection_schedule_no',"SC001");
        $collection_schedule->save();

        foreach ($request->collection_amounts as $collection_amount){
            //dd($collection_amount);
            $cs_items[] = new CollectionScheduleItem($collection_amount);
        }
        $collection_schedule->items()->saveMany($cs_items);

        Session::put('alert-success', 'Collection Schedule created successfully');
        return redirect()->route('collection-schedule.index');
    }

   
    public function show(CollectionSchedule $collectionSchedule)
    {
        //
    }

    public function edit(CollectionSchedule $collectionSchedule)
    {
        //
    }

    public function update(Request $request, CollectionSchedule $collectionSchedule)
    {
        //
    }

    public function destroy(CollectionSchedule $collectionSchedule)
    {
        //
    }
}

app/Http/Controllers/Sales/CreditRuleController.php
<?php

namespace App\Http\Controllers\Sales;

use App\CreditRule;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;
use Auth;
use Session;
use Carbon\Carbon;

class CreditRuleController extends Controller
{
    private $view_root = 'modules/sales/setting/rule_setup/';
    public function index()
    {
        $view = view($this->view_root . 'credit_rule');
        $view->with('credit_rule', new CreditRule);
        $view->with('customer_list', Customer::pluck('name', 'id')->prepend('',''));
        $view->with('credit_rule_list', CreditRule::orderBy('id', 'desc')->get());
        return $view;
    }

    public function create()
    {
        $view = view($this->view_root . 'create');
        return $view;
    }

    public function store(Request $request)
    {
        $request->validate([
            'customer_id' => 'required|unique:credit_rules',
            'credit_amount' => 'required',
            'days' => 'required',
        ]);
        $credit_rule = new CreditRule;
        $credit_rule->fill($request->input());
        $credit_rule->creator_user_id = Auth::id();
        $credit_rule->save();
        Session::put('alert-success', 'New credit rule added successfully!');
        return redirect()->back();
    }

    public function show(CreditRule $creditRule)
    {
        //
    }

    public function edit(CreditRule $creditRule)
    {
        //
    }

    public function update(Request $request, CreditRule $creditRule)
    {
        //
    }

    public function destroy(CreditRule $creditRule)
    {
        //
    }
}

app/Http/Controllers/Sales/CustomerZoneController.php
<?php

namespace App\Http\Controllers\Sales;
use App\Http\Controllers\Controller;
use App\CustomerZone;
use App\City;
use Illuminate\Http\Request;
use Auth;
use Session;

class CustomerZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $view_root = 'modules/sales/setting/customer_zone/';
    public function index()
    {
        $view = view($this->view_root . 'index');
        $view->with('customer_zone_list', CustomerZone::all());
        return $view;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view($this->view_root . 'create');
        $view->with('city_list', City::pluck('name', 'id'));
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // dd( $request->input());
        $request->validate([
            'name' => 'required|unique:customer_zones',
            'short_name' => 'required|unique:customer_zones',
            'city_ids' => 'required'
        ]);
        $customer_zone = new CustomerZone;
        $customer_zone->fill($request->input());
        $customer_zone->creator_user_id = Auth::id();
        $customer_zone->save();

        $customer_zone->zone_cities()->sync($request->city_ids);

        Session::put('alert-success', 'Customer zone created successfully');
        return redirect()->route('customer-zone.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\CustomerZone  $customerZone
     * @return \Illuminate\Http\Response
     */
    public function show(CustomerZone $customerZone)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\CustomerZone  $customerZone
     * @return \Illuminate\Http\Response
     */
    public function edit(CustomerZone $customerZone)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\CustomerZone  $customerZone
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CustomerZone $customerZone)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CustomerZone  $customerZone
     * @return \Illuminate\Http\Response
     */
    public function destroy(CustomerZone $customerZone)
    {
        //
    }
}

resources/views/modules/sales/sales_order_cancel/create.blade.php
@extends('layout')
@section('title', 'Sales Order Cancel')
@section('content')
<!-- page content -->
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Sales Order Cancel</h2>
                    <a href="{{ route('sales-order-cancel.index')}}" class="btn btn-sm btn-primary btn-addon pull-right"><i class="fa fa-list-ul" aria-hidden="true"></i> Sales Order Cancel List</a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @include('partials.flash_msg')
                    <form class="form-horizontal form-label-left input_mask" action="{{ route('sales-order-cancel.store') }}" method="POST" autocomplete="off">
                        @csrf
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                {{ BootForm::select('sales_order_id', 'Sales Order No', $sales_order_list, null, ['class'=>'form-control input-sm select2', 'ng-model'=>'sales_order_id', 'data-placeholder'=>'Select Sales Order No', 'required','data-popup'=> route('sales-order.index')]) }}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                {{ BootForm::select('sales_order_cancel_reason_id', 'Reason', $sales_order_cancel_reason_list, null, ['class'=>'form-control input-sm select2', 'ng-model'=>'sales_order_cancel_reason_id', 'data-placeholder'=>'Select Reason', 'required','data-popup'=> route('sales-order-cancel-reason.index')]) }}
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                {{ BootForm::textarea('remarks','Remarks', NULL, ['class'=>'form-control input-sm','rows'=>2]) }}
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <br />
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-sm">Save</button>
                                    <a href="{{ route('sales-order-cancel.index')}}" class="btn btn-default btn-sm">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')

@endsection

resources/views/modules/sales/sales_order_cancel/index.blade.php
@extends('layout')
@section('title', 'Sales Order Cancel')
@section('content')

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Sales</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Sales Order Cancel</h2>
                        <a href="{{ route('sales-order-cancel.create') }}" class="btn btn-sm btn-primary btn-addon pull-right"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New</a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover datatable-buttons">
                                <thead class="bg-primary">
                                    <tr>
                                        <th width="35">#</th>
                                        <th>Sales Order Cancel No</th>
                                        <th>Sales Order No</th>
                                        <th>Reason</th>
                                        <th width="35" class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($sales_order_cancel_list as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->sales_order_cancel_no }}</td>
                                        <td>{{ $item->sales_order->sales_order_no}}</td>
                                        <td>{{ $item->sales_order_cancel_reason->name}}</td>
                                        <td class="text-center">
                                            <a href="{{ route('sales-order-cancel.show', $item ) }}" class="btn btn-block btn-sm btn-default btn-xs"><i class="fa fa-eye"></i>View</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!--end table-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
@endsection